export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_RESET = "GET_USERS_RESET";

export const ADD_SELECTED_USER = "ADD_SELECTED_USER";
export const REMOVE_SELECTED_USER = "REMOVE_SELECTED_USER";
export const SET_SELECTED_USERS = "SET_SELECTED_USERS";

export const SET_DRAGGING = "SET_DRAGGING";
export const SET_DRAGGING_USER = "SET_DRAGGING_USER";
export const SET_DRAGGING_CARD_SELECTED = "SET_DRAGGING_CARD_SELECTED";

export const SET_FILTER = "SET_FILTER";
